Repository Johngtka/BioMagnetic-app, pull requests merged in 2023-02, with the labels that each got.

#8 Responsive Side Bar
  package-lock.json
  package.json
  src/app/about/about.component.css
  src/app/about/about.component.html
  src/app/about/about.component.spec.ts
  src/app/about/about.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/patient-search/patient-search.component.css
  src/app/patient-search/patient-search.component.html
  src/app/patient-search/patient-search.component.ts
  src/assets/api/biomag.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/pl.json
  src/assets/img/user.svg
  src/index.html
  tsconfig.json
Labels: enhancement

#11 Patients Table
  src/app/app.component.css
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/patient-table/patient-table.component.css
  src/app/patient-table/patient-table.component.html
  src/app/patient-table/patient-table.component.spec.ts
  src/app/patient-table/patient-table.component.ts
  src/app/services/patient-service.ts
  src/app/services/snack.service.ts
  src/assets/api/biomag.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/pl.json
Labels: enhancement

#12 Git hooks
  .eslintrc.js
  .husky/pre-commit
  .prettierrc
  angular.json
  package-lock.json
  package.json
  src/app/about/about.component.spec.ts
  src/app/about/about.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/models/patient.ts
  src/app/patient-search/patient-search.component.css
  src/app/patient-search/patient-search.component.html
  src/app/patient-search/patient-search.component.spec.ts
  src/app/patient-search/patient-search.component.ts
  src/app/patient-table/patient-table.component.html
  src/app/patient-table/patient-table.component.spec.ts
  src/app/patient-table/patient-table.component.ts
  src/app/services/patient-service.spec.ts
  src/app/services/patient-service.ts
  src/app/services/snack.service.spec.ts
  src/app/services/snack.service.ts
  src/assets/api/biomag.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/pl.json
  src/index.html
  src/main.ts
  src/styles.css
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
Labels: chore

#14 Revert mockoon to working version
  .husky/pre-commit
  src/assets/api/biomag.json
Labels: bug

#15 Show 'loading' notification when searching for patients
  src/app/patient-search/patient-search.component.html
  src/assets/api/biomag.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/pl.json
Labels: bug
